# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aed7fec01c768285ab7550fc2841a6368b04d7754bed8d3b6ff391492ad2f5cec5e89c8f05c3ea27ee8692c474296500b8801766c443992ff1ecff7be33c1d0

test:
  secret_key_base: 2a205a1017c6ed2e9a1820f361c04c8ae961e0ebe28a138645d4e9a4b86517991ba12bbdf1c50e94a8150efc15972494457c9a9ca91eea3d2474f1aa267a5261

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
